// Copyright 2025 The Torch-Spyre Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License").
//
//! REAL-MODEL end-to-end — hermetic w.r.t. the scratchy `.cache`.
//!
//! Each test runs a real forward of a real model: the KTIR *program* is vendored
//! in-repo (`tests/fixtures/<model>/` — `manifest.json` + `node*.mlir`, no
//! weights), and the *weights* are fetched from a PUBLIC HuggingFace repo (no
//! `HF_TOKEN`) via `hf-hub` and read with the `safetensors` crate. Nothing reads
//! `~/.cache/cudaforge`.
//!
//! Correctness is checked against a REAL-MODEL GOLDEN: the production path
//! (`execute_segmented` — fuse + GPU/AMX offload + head-parallel attention) must
//! reproduce the `transformers` logits (vendored as `golden.f16.gz`, regenerated by
//! `tests/fixtures/gen_golden.py`). The per-row next-token argmax must match the
//! real model; `max_abs` is reported and loosely bounded (f16 over many layers vs
//! an f32 golden drifts). This catches fusion/offload/marshal/weight-layout bugs.
//!
//! Weights are PyTorch linear weights (`[out,in]`), bound VERBATIM / zero-copy as
//! f16 — NO transpose at load. The KTIR program contracts the correct axis itself
//! (`matmul_transpose_b`). Runtime activations the program expects but that aren't
//! HF weights — the input activation (`role:embed`), RoPE `cos`/`sin`, the (empty)
//! KV-cache `prefix_k`/`prefix_v`, and the attention mask — come from the vendored
//! `t<id>.f16.gz` the generator wrote from the same model forward.
//!
//! NOT `#[ignore]` / NOT env-gated: runs in default `cargo test`. Weights are
//! fetched from HF (content-addressed, cached). Prefill (m>1) is `cfg(metal)` —
//! the fused [1,1] segments need the offload for full-M reconstruction.

#![cfg(feature = "optimizer")]

use ktir_cpu::dtypes::DType;
use ktir_cpu::interpreter::Arg;
use ktir_cpu::ir::IRModule;
use ktir_cpu::parser::parse_module;
use ktir_optimizer::fusion::{Binding, NodeSpec, ProgramSpec};
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

fn fixture_dir(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Read a gzip'd, headerless, row-major little-endian **f16** `.f16.gz` (the
/// vendored golden / runtime-input convention written by `gen_golden.py`) and
/// widen to f32. f16 because Spyre runs f16 (the program is f16, so f32 storage is
/// needless and the `max_abs` band is looser than f16); gzip -9 because the
/// constant tensors (zero KV-prefix, identity cos/sin, all-masked mask) compress to
/// ~nothing.
fn read_f16_gz(path: &Path) -> Vec<f32> {
    use std::io::Read;
    let file = std::fs::File::open(path).unwrap_or_else(|e| panic!("open {path:?}: {e}"));
    let mut bytes = Vec::new();
    flate2::read::GzDecoder::new(file)
        .read_to_end(&mut bytes)
        .unwrap_or_else(|e| panic!("gunzip {path:?}: {e}"));
    ktir_cpu::codec::decode(&bytes, bytes.len() / 2, DType::F16)
}

fn argmax(v: &[f32]) -> usize {
    v.iter()
        .enumerate()
        .fold((0, f32::NEG_INFINITY), |(bi, bv), (i, &x)| {
            if x > bv { (i, x) } else { (bi, bv) }
        })
        .0
}

/// A vendored program: module + spec + the metadata to marshal sources.
struct Program {
    module: IRModule,
    spec: ProgramSpec,
    /// tensor id -> (rows, cols)
    shape: HashMap<u64, (usize, usize)>,
    /// source id -> (role, optional HF disk-name) from manifest `sources[]`
    src_meta: HashMap<u64, (String, Option<String>)>,
    is_source: HashSet<u64>,
    mask_id: Option<u64>,
    result_id: u64,
}

fn load_program(dir: &Path) -> Program {
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(dir.join("manifest.json")).unwrap()).unwrap();

    let mut shape = HashMap::new();
    let mut is_source = HashSet::new();
    for t in manifest["tensors"].as_array().unwrap() {
        let id = t["id"].as_u64().unwrap();
        shape.insert(
            id,
            (
                t["rows"].as_u64().unwrap() as usize,
                t["cols"].as_u64().unwrap() as usize,
            ),
        );
        if t["is_source"].as_bool().unwrap_or(false) {
            is_source.insert(id);
        }
    }
    let mut src_meta = HashMap::new();
    for s in manifest["sources"].as_array().unwrap() {
        let id = s["id"].as_u64().unwrap();
        let role = s["role"].as_str().unwrap_or("weight").to_string();
        let disk = s["disk"].as_str().map(|x| x.to_string());
        src_meta.insert(id, (role, disk));
    }
    let result_id = manifest["result"].as_u64().unwrap();
    let mask_id = manifest["attn_mask"].as_u64();

    let mut sources: HashSet<u64> = is_source.clone();
    if let Some(m) = mask_id {
        sources.insert(m);
    }

    let mut module = IRModule::default();
    let mut nodes = Vec::new();
    for node in manifest["nodes"].as_array().unwrap() {
        let func = node["fn"].as_str().unwrap().to_string();
        let mlir = node["mlir"].as_str().unwrap();
        let parsed = parse_module(&std::fs::read_to_string(dir.join(mlir)).unwrap())
            .unwrap_or_else(|e| panic!("parse {mlir}: {e}"));
        for (_, f) in parsed.functions {
            module.add_function(f);
        }
        let bindings = node["args"]
            .as_array()
            .unwrap()
            .iter()
            .map(|a| Binding {
                arg: format!("%{}", a["name"].as_str().unwrap()),
                tensor: a["tensor"].as_u64().unwrap(),
                is_output: a["is_output"].as_bool().unwrap_or(false),
            })
            .collect();
        nodes.push(NodeSpec { func, bindings });
    }
    let spec = ProgramSpec {
        nodes,
        sources,
        results: HashSet::from([result_id]),
    };
    Program {
        module,
        spec,
        shape,
        src_meta,
        is_source,
        mask_id,
        result_id,
    }
}

// ---------------------------------------------------------------------------
// Real weights from a public HF repo (no token) via hf-hub + safetensors.
// ---------------------------------------------------------------------------

/// Open a repo's safetensors as a `name -> bf16 f16-bytes` resolver. Handles
/// single-file (`model.safetensors`) and sharded (`*.index.json`) layouts.
struct Weights {
    /// shard file bytes, kept alive for the views to borrow
    blobs: Vec<Vec<u8>>,
    /// tensor name -> f16 bytes already converted from bf16 (verbatim PyTorch `[out,in]`,
    /// bound zero-copy — the program's `matmul_transpose_b` reads this layout directly).
    f16: HashMap<String, Vec<u8>>,
}

impl Weights {
    /// Returns `None` (skip the test) if the repo can't be fetched (offline /
    /// HF down) — so a network-less box degrades gracefully rather than failing
    /// spuriously; a box WITH network exercises the real path.
    fn fetch(repo: &str) -> Option<Weights> {
        let api = hf_hub::api::sync::Api::new().ok()?;
        let model = api.model(repo.to_string());

        // Collect the safetensors shard filenames.
        let shard_files: Vec<String> = match model.get("model.safetensors.index.json") {
            Ok(idx) => {
                let j: serde_json::Value =
                    serde_json::from_slice(&std::fs::read(idx).ok()?).ok()?;
                let mut set = std::collections::BTreeSet::new();
                for v in j["weight_map"].as_object()?.values() {
                    set.insert(v.as_str()?.to_string());
                }
                set.into_iter().collect()
            }
            Err(_) => vec!["model.safetensors".to_string()],
        };

        let mut blobs = Vec::new();
        for f in &shard_files {
            let path = model.get(f).ok()?;
            blobs.push(std::fs::read(path).ok()?);
        }
        // Eagerly convert every tensor's bf16 bytes -> f16 bytes (the stick
        // layout). bf16 is the on-disk dtype for these models.
        let mut f16 = HashMap::new();
        for b in &blobs {
            let st = safetensors::SafeTensors::deserialize(b).ok()?;
            for (name, view) in st.tensors() {
                let raw = view.data();
                let n = raw.len() / 2;
                // bf16 LE bytes -> f16 LE bytes via the crate codec.
                let as_f16 = ktir_cpu::codec::bf16_to_f16(raw, n);
                f16.insert(name.to_string(), as_f16);
            }
        }
        Some(Weights { blobs, f16 })
    }

    /// Verbatim f16 bytes for `<disk>.weight` in PyTorch `[out,in]` order — bound
    /// zero-copy, NO transpose. The KTIR program is responsible for contracting the
    /// correct axis (via `matmul_transpose_b`). Tied lm_head falls back to
    /// `embed_tokens.weight`.
    fn weight(&self, disk: &str) -> Option<&[u8]> {
        if let Some(v) = self.f16.get(&format!("{disk}.weight")) {
            return Some(v);
        }
        if disk == "lm_head" {
            return self
                .f16
                .get("model.embed_tokens.weight")
                .map(|v| v.as_slice());
        }
        None
    }
}

/// Deterministic synthetic activation for a non-weight source, used only as a
/// pre-generation fallback when a vendored `t<id>.f16.gz` is absent. RoPE-valid
/// (cos=1, sin=0 = identity rotation) so the forward stays finite.
fn synth(role: &str, n: usize) -> Vec<f32> {
    match role {
        "cos" => vec![1.0; n],
        "sin" => vec![0.0; n],
        // input activation / KV-cache prefixes: small bounded deterministic.
        _ => (0..n).map(|i| ((i % 17) as f32 - 8.0) * 0.01).collect(),
    }
}

/// Build the source args (keyed `t{id}`). Real f16 weights from HF; the runtime
/// activations (input activation, RoPE cos/sin, KV prefix) come from the VENDORED
/// `t<id>.f16.gz` the generator wrote from the real model forward, so production is
/// fed exactly what the `golden.f16.gz` was computed against. (A missing file falls
/// back to a deterministic synth so the loader still runs pre-generation.)
fn build_args(dir: &Path, p: &Program, w: &Weights) -> Vec<(String, Arg)> {
    let mut args = Vec::new();
    let mut ids: Vec<u64> = p.is_source.iter().copied().collect();
    if let Some(m) = p.mask_id
        && !ids.contains(&m)
    {
        ids.push(m);
    }
    ids.sort_unstable();
    let m_valid = p
        .src_meta
        .iter()
        .find(|(_, (role, _))| role == "embed")
        .map(|(id, _)| p.shape[id].0)
        .unwrap_or(1);
    for id in ids {
        let (rows, cols) = p.shape[&id];
        let n = rows * cols;
        let key = format!("t{id}");
        let vendored = dir.join(format!("t{id}.f16.gz"));

        // Weight sources: always from HF (verbatim f16 bytes).
        if let Some((_, Some(d))) = p.src_meta.get(&id) {
            let bytes = w
                .weight(d)
                .unwrap_or_else(|| panic!("HF weight {d:?} (t{id}) not found in repo"));
            assert_eq!(
                bytes.len(),
                n * 2,
                "weight {d} (t{id}) numel {} != {n}",
                bytes.len() / 2
            );
            args.push((
                key,
                Arg::TensorBytes {
                    data: bytes.to_vec(),
                    shape: vec![rows, cols],
                    dtype: DType::F16,
                },
            ));
            continue;
        }

        // Runtime activations: prefer the vendored real tensor (generated from the
        // model forward); else fall back to a deterministic synth.
        let data = if vendored.is_file() {
            let v = read_f16_gz(&vendored);
            assert_eq!(v.len(), n, "vendored t{id} len {} != {n}", v.len());
            v
        } else if Some(id) == p.mask_id {
            // The mask applies to the 64-position prefix KV CACHE, which is EMPTY
            // for a fresh forward (the current token(s) enter via a separate fresh
            // K/V path, not through this mask). So mask ALL prefix positions (f16-min
            // additive ≈ -inf) — attention then uses only the fresh tokens.
            let _ = m_valid;
            vec![-65504.0; n]
        } else {
            let role = p
                .src_meta
                .get(&id)
                .map(|(r, _)| r.as_str())
                .unwrap_or("weight");
            match role {
                "prefix_k" | "prefix_v" => vec![0.0; n],
                _ => synth(role, n),
            }
        };
        args.push((
            key,
            Arg::Tensor {
                data,
                shape: vec![rows, cols],
                dtype: DType::F16,
            },
        ));
    }
    args
}

/// Production path: the real serving API — fuse into ordered segments and run
/// each (fused [1,1] GPU/AMX offload + native head-parallel attention).
fn forward_production(p: &Program, args: &[(String, Arg)]) -> Vec<f32> {
    let refs: Vec<(&str, Arg)> = args.iter().map(|(n, a)| (n.as_str(), a.clone())).collect();
    let key = format!("t{}", p.result_id);
    let out = ktir_cpu::segmented::execute_segmented(&p.module, &p.spec, &refs, &[&key])
        .expect("execute_segmented");
    out.get(&key).expect("result").data.clone()
}

/// Run a real model forward and assert the production output matches the
/// REAL-MODEL golden (transformers logits, vendored as `golden.f16.gz` by
/// `gen_golden.py`). Skips if the golden isn't present (not generated) or the repo
/// can't be fetched (offline). The primary check is the next-token argmax of the
/// last row; `max_abs` is reported and bounded (f16 over many layers vs an f32
/// golden drifts, so the band is loose — argmax is the real assertion).
fn real_forward_golden(fixture: &str, repo: &str) {
    let dir = fixture_dir(fixture);
    if !dir.join("golden.f16.gz").is_file() {
        eprintln!(
            "{fixture}: no vendored golden.f16.gz (run tests/fixtures/gen_golden.py) — skipping"
        );
        return;
    }
    let p = load_program(&dir);
    let Some(w) = Weights::fetch(repo) else {
        eprintln!("{fixture}: could not fetch {repo} (offline?) — skipping");
        return;
    };
    let _ = &w.blobs; // kept alive
    let args = build_args(&dir, &p, &w);
    let prod = forward_production(&p, &args);
    let golden = read_f16_gz(&dir.join("golden.f16.gz"));

    assert_eq!(
        prod.len(),
        golden.len(),
        "{fixture}: result {} != golden {}",
        prod.len(),
        golden.len()
    );
    assert!(
        prod.iter().all(|x| x.is_finite()),
        "{fixture}: non-finite production output"
    );

    let (m, vocab) = p.shape[&p.result_id];
    assert_eq!(m * vocab, prod.len(), "{fixture}: result shape {m}x{vocab}");
    // Per-row next-token argmax must match the real model (the meaningful check).
    let mut argmax_hits = 0usize;
    for r in 0..m {
        let row = r * vocab..(r + 1) * vocab;
        if argmax(&prod[row.clone()]) == argmax(&golden[row]) {
            argmax_hits += 1;
        }
    }
    let max_abs = prod
        .iter()
        .zip(&golden)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    eprintln!(
        "{fixture} via {repo}: [{m},{vocab}] logits, argmax {argmax_hits}/{m} rows match golden, \
         max abs diff {max_abs:.4}"
    );
    assert_eq!(
        argmax_hits, m,
        "{fixture}: next-token argmax disagrees with the real model"
    );
    assert!(
        max_abs < 1.0,
        "{fixture}: logits diverge from golden by {max_abs}"
    );
}

#[test]
fn smollm2_135m_decode_real_forward() {
    real_forward_golden("smollm2-135m", "HuggingFaceTB/SmolLM2-135M");
}

#[test]
fn llama_3_2_1b_decode_real_forward() {
    real_forward_golden("llama-3.2-1b", "unsloth/Llama-3.2-1B-Instruct");
}

// PREFILL (m>1) requires `cfg(metal)`: the fused [1,1] segments need the GPU/AMX
// offload for full-M reconstruction (without it they compute only row 0). Run with
// `--features metal`.
#[cfg(feature = "metal")]
#[test]
fn smollm2_135m_prefill_real_forward() {
    real_forward_golden("smollm2-135m-prefill", "HuggingFaceTB/SmolLM2-135M");
}

#[cfg(feature = "metal")]
#[test]
fn llama_3_2_1b_prefill_real_forward() {
    real_forward_golden("llama-3.2-1b-prefill", "unsloth/Llama-3.2-1B-Instruct");
}
